version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    networks:
      - net-php

  php:
    build: .
    image: zhanbing/php71
    container_name: lnmp-php
    expose:
      - "9000"
    volumes:
      - ./www:/var/www/html:cached
      - ./conf/php/php.ini:/usr/local/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./log/php:/var/log/php:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:5.7
    container_name: lnmp-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql-data/:/var/lib/mysql/
      - ./log/mysql/:/var/log/mysql/
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:latest
    container_name: lnmp-redis
    networks:
      - net-redis
    ports:
      - "6379:6379"

networks:
  net-php:
  net-mysql:
  net-redis:
